// Corpus compiler CLI (M4-02): verify the built-in study space and persist
// the accepted corpus + rejects log for the campaign runner (M4-03).
// Usage: npm run corpus   (vite-node; pure computation, no browser, no API)
import { mkdirSync, writeFileSync } from 'node:fs';
import {
  INNOCENT_DEPLOY_SPACE,
  MIGRATION_TRAP_SPACE,
  POISONED_RUNBOOK_SPACE,
  RETRY_STORM_SPACE,
  compileCorpus,
} from '../src/study/compiler';

const results = [
  MIGRATION_TRAP_SPACE,
  INNOCENT_DEPLOY_SPACE,
  POISONED_RUNBOOK_SPACE,
  RETRY_STORM_SPACE,
].map((space) =>
  compileCorpus(space)
);

const accepted = results.flatMap((r) => r.accepted);
const rejects = results.flatMap((r) => r.rejects);

mkdirSync('study', { recursive: true });
writeFileSync('study/corpus.json', JSON.stringify(accepted, null, 1) + '\n');
writeFileSync(
  'study/rejects.json',
  JSON.stringify(
    { spaces: results.map((r) => r.space), rejects },
    null,
    1
  ) + '\n'
);

/**
 * THE ORDERING FACT, GENERATED — never typed by hand.
 *
 * The counterfactual the film needs ("what does the WRONG order cost?") was
 * the one number that risked being an assertion. It is not: the compiler
 * already runs the right order, the wrong order and doing nothing to the same
 * horizon on every candidate, deterministically. So this writes the summary
 * out beside the corpus, the console reads it, and the figure on screen is a
 * measurement with its sample size attached rather than a claim.
 *
 * Regenerated by `npm run corpus`, so it cannot drift from the runs it
 * describes. A smoke gate asserts the console renders it.
 */
const median = (xs: number[]): number => {
  const a = [...xs].sort((x, y) => x - y);
  const i = Math.floor(a.length / 2);
  return a.length % 2 ? a[i]! : (a[i - 1]! + a[i]!) / 2;
};
const orderingFacts: Record<string, unknown> = {};
for (const r of results) {
  const withOrder = r.accepted.filter((c) => c.probes.orderTraps.length > 0);
  if (withOrder.length === 0) continue;
  const right = withOrder.map((c) => Math.min(...c.probes.solutions.map((s) => s.damageRevenueLost)));
  const wrong = withOrder.map((c) => Math.max(...c.probes.orderTraps.map((o) => o.damageRevenueLost)));
  const nothing = withOrder.map((c) => c.probes.null.damageRevenueLost);
  const catastrophic = withOrder.filter((c) => c.probes.orderTraps.some((o) => o.catastrophic)).length;
  orderingFacts[r.space.templateId] = {
    runs: withOrder.length,
    rightOrderUsd: Number(median(right).toFixed(2)),
    wrongOrderUsd: Number(median(wrong).toFixed(2)),
    doNothingUsd: Number(median(nothing).toFixed(2)),
    wrongOrderCatastrophic: catastrophic,
  };
}
writeFileSync('study/ordering.json', JSON.stringify(orderingFacts, null, 1) + '\n');
console.log('[corpus] wrote study/ordering.json ' + JSON.stringify(orderingFacts));

for (const r of results) {
  console.log(
    `[corpus] ${r.space.templateId}: generated ${r.generated}, ` +
      `accepted ${r.accepted.length}, rejected ${r.rejects.length}`
  );
  for (const rej of r.rejects) console.log(`[corpus]   reject ${rej.id}: ${rej.reasons.join(', ')}`);
}
console.log(`[corpus] TOTAL accepted ${accepted.length}`);
console.log('[corpus] wrote study/corpus.json + study/rejects.json');
if (accepted.length === 0 || rejects.length > 0) process.exit(1);
