// Corpus compiler CLI (M4-02): verify the built-in study space and persist
// the accepted corpus + rejects log for the campaign runner (M4-03).
// Usage: npm run corpus   (vite-node; pure computation, no browser, no API)
import { mkdirSync, writeFileSync } from 'node:fs';
import {
  INNOCENT_DEPLOY_SPACE,
  MIGRATION_TRAP_SPACE,
  POISONED_RUNBOOK_SPACE,
  RETRY_STORM_SPACE,
  compileCorpus,
} from '../src/study/compiler';
import { metaFor } from '../src/sim/templates';

const results = [
  MIGRATION_TRAP_SPACE,
  INNOCENT_DEPLOY_SPACE,
  POISONED_RUNBOOK_SPACE,
  RETRY_STORM_SPACE,
].map((space) =>
  compileCorpus(space)
);

const accepted = results.flatMap((r) => r.accepted);
const rejects = results.flatMap((r) => r.rejects);

mkdirSync('study', { recursive: true });
writeFileSync('study/corpus.json', JSON.stringify(accepted, null, 1) + '\n');
writeFileSync(
  'study/rejects.json',
  JSON.stringify(
    { spaces: results.map((r) => r.space), rejects },
    null,
    1
  ) + '\n'
);

/**
 * THE ORDERING FACT, GENERATED — never typed by hand.
 *
 * The counterfactual the film needs ("what does the WRONG order cost?") was
 * the one number that risked being an assertion. It is not: the compiler
 * already runs the right order, the wrong order and doing nothing to the same
 * horizon on every candidate, deterministically. So this writes the summary
 * out beside the corpus, the console reads it, and the figure on screen is a
 * measurement with its sample size attached rather than a claim.
 *
 * Regenerated by `npm run corpus`, so it cannot drift from the runs it
 * describes. A smoke gate asserts the console renders it.
 */
const median = (xs: number[]): number => {
  const a = [...xs].sort((x, y) => x - y);
  const i = Math.floor(a.length / 2);
  return a.length % 2 ? a[i]! : (a[i - 1]! + a[i]!) / 2;
};
/**
 * NOT EVERY ORDER TRAP IS "THE SAME LEVERS REVERSED", and conflating them is
 * an overclaim. retry-storm declares three: rollforward-then-cap and
 * rollback-then-cap (the plan's own actions in the wrong sequence, ~$170), and
 * silence-then-ship (a DIFFERENT action set, catastrophic in 24 of 24, ~$538).
 * Taking the max across all three and calling it "reversed" shipped a receipt
 * that put the silence figure on the reversal. Classify by whether the trap is
 * a PERMUTATION of a declared solution: that is the reversal, and the rest are
 * reported as the worst wrong move, separately and by name.
 */
const sameSet = (a: string[], b: string[]): boolean =>
  a.length === b.length && [...a].sort().join('|') === [...b].sort().join('|');

const orderingFacts: Record<string, unknown> = {};
for (const r of results) {
  const withOrder = r.accepted.filter((c) => c.probes.orderTraps.length > 0);
  if (withOrder.length === 0) continue;
  const right: number[] = [];
  const reversed: number[] = [];
  const worst: number[] = [];
  const nothing: number[] = [];
  let worstCatastrophic = 0;
  let reversedCatastrophic = 0;
  for (const c of withOrder) {
    const meta = metaFor(c.candidate.templateId, c.candidate.params);
    if (!meta) continue;
    right.push(Math.min(...c.probes.solutions.map((s) => s.damageRevenueLost)));
    nothing.push(c.probes.null.damageRevenueLost);
    const rev = (meta.orderTraps ?? [])
      .map((seq, i) => ({ seq, run: c.probes.orderTraps[i] }))
      .filter((x) => x.run && meta.solutions.some((sol) => sameSet(sol, x.seq)));
    if (rev.length) {
      reversed.push(Math.max(...rev.map((x) => x.run!.damageRevenueLost)));
      if (rev.some((x) => x.run!.catastrophic)) reversedCatastrophic++;
    }
    worst.push(Math.max(...c.probes.orderTraps.map((o) => o.damageRevenueLost)));
    if (c.probes.orderTraps.some((o) => o.catastrophic)) worstCatastrophic++;
  }
  if (reversed.length === 0) continue;
  orderingFacts[r.space.templateId] = {
    runs: reversed.length,
    rightOrderUsd: Number(median(right).toFixed(2)),
    reversedUsd: Number(median(reversed).toFixed(2)),
    reversedCatastrophic,
    worstOrderUsd: Number(median(worst).toFixed(2)),
    worstOrderCatastrophic: worstCatastrophic,
    doNothingUsd: Number(median(nothing).toFixed(2)),
  };
}
writeFileSync('study/ordering.json', JSON.stringify(orderingFacts, null, 1) + '\n');
console.log('[corpus] wrote study/ordering.json ' + JSON.stringify(orderingFacts));

for (const r of results) {
  console.log(
    `[corpus] ${r.space.templateId}: generated ${r.generated}, ` +
      `accepted ${r.accepted.length}, rejected ${r.rejects.length}`
  );
  for (const rej of r.rejects) console.log(`[corpus]   reject ${rej.id}: ${rej.reasons.join(', ')}`);
}
console.log(`[corpus] TOTAL accepted ${accepted.length}`);
console.log('[corpus] wrote study/corpus.json + study/rejects.json');
if (accepted.length === 0 || rejects.length > 0) process.exit(1);
