import { chromium } from 'playwright';
import { mkdirSync } from 'node:fs';
const OUT = process.argv[2] ?? 'log/sid';
const URL = process.argv[3] ?? 'http://localhost:8917/?review=plan';
const NAME = process.argv[4] ?? 'shot';
mkdirSync(OUT, { recursive: true });
const b = await chromium.launch();
const page = await b.newPage({ viewport: { width: 1512, height: 945 } });
const errs = [];
page.on('pageerror', e => errs.push(String(e)));
await page.goto(URL, { waitUntil: 'networkidle' });
await page.waitForTimeout(3500);
await page.screenshot({ path: `${OUT}/${NAME}.png` });
console.log('shot ->', `${OUT}/${NAME}.png`, errs.length ? `ERRORS: ${errs}` : 'no page errors');
await b.close();
