import { chromium } from 'playwright';
import { mkdirSync, readFileSync } from 'node:fs';
const [,, OUT='log/type', URL='http://localhost:8917/?review=plan', NAME='shot', CSSFILE='', WAIT='12000'] = process.argv;
mkdirSync(OUT, { recursive: true });
const b = await chromium.launch();
const page = await b.newPage({ viewport: { width: 1512, height: 945 } });
const errs = []; page.on('pageerror', e => errs.push(String(e)));
await page.goto(URL, { waitUntil: 'networkidle' });
if (CSSFILE) await page.addStyleTag({ content: readFileSync(CSSFILE, 'utf8') });
await page.waitForTimeout(Number(WAIT));
if (CSSFILE) await page.addStyleTag({ content: readFileSync(CSSFILE, 'utf8') });
await page.waitForTimeout(300);
await page.screenshot({ path: `${OUT}/${NAME}.png` });
console.log('shot ->', `${OUT}/${NAME}.png`, errs.length ? `ERRORS: ${errs}` : 'ok');
await b.close();
